---

- hosts: all
  become: true
  tasks:


  - name: Update (Ubuntu)
    apt:
      state: latest
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Installing Docker (Ubuntu)
    apt:
      name: docker.io
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Start Docker
    service:
      name: docker
      state: restarted

  - name: Add docker to Group
    ansible.builtin.group:
      name: seludo-docker
      state: present

  - name: Copy Docker file
    copy:
      src: dockerfile
      dest: /seludo/docker/


